package:
    name: neuclease

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    version: {{GIT_DESCRIBE_TAG}}.post{{GIT_DESCRIBE_NUMBER}}
  {% else %}
    version: {{GIT_DESCRIBE_TAG}}
  {% endif %}

source:
  path: ../

build:
  number: 0
  string: {{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.6,{{ python }}*
    - setuptools

  run:
    - python {{ python }}*
    - requests
    - flask >=1.0
    - numpy >=1.13
    - h5py
    - pandas <1.0
    - numba >=0.45
    - vigra
    - pillow
    - nifty
    - libdvid-cpp >=0.3.post83
    - dvidutils >=0.0.post81
    - tqdm
    - ujson
    - pykafka
    - networkx >=2.1
    - asciitree
    - protobuf 3.9.1
    #- graph-tool  <-- Optional dependency. Install to your own conda env if desired (but check the license).

test:
  requires:
    - pytest
    - dvid >=dvid-0.9.6.post64
    - libdvid-cpp

  imports:
    - neuclease

  commands:
    - pytest -s --tb=native --pyargs neuclease.tests

about:
  home: https://github.com/janelia-flyem/neuclease
  license: BSD (3-clause)
  summary: Tools for computing interactive "cleaves" of agglomerated neuron fragments from a DVID server.
