# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: neuclease/dvid/keyvalue/ingest.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'neuclease/dvid/keyvalue/ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$neuclease/dvid/keyvalue/ingest.proto\x12\x08keyvalue\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x14\n\x04Keys\x12\x0c\n\x04keys\x18\x01 \x03(\t\",\n\tKeyValues\x12\x1f\n\x03kvs\x18\x01 \x03(\x0b\x32\x12.keyvalue.KeyValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neuclease.dvid.keyvalue.ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYVALUE']._serialized_start=50
  _globals['_KEYVALUE']._serialized_end=88
  _globals['_KEYS']._serialized_start=90
  _globals['_KEYS']._serialized_end=110
  _globals['_KEYVALUES']._serialized_start=112
  _globals['_KEYVALUES']._serialized_end=156
# @@protoc_insertion_point(module_scope)
